# DO NOT CHANGE the "init" and "install" sections below

environment:
  global:
    R_VERSION: stable
    NOT_CRAN: true

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary


# Adapt as necessary starting from here

services:
  - mssql2014

build_script:
  - travis-tool.sh install_deps
  - travis-tool.sh install_github jimhester/DBItest@bit64

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

on_success:
  - R -e "covr::codecov(line_exclusions = c('src/nanodbc.h', 'src/nanodbc.cpp', 'src/cctz/include/civil_time_detail.h', 'src/cctz/include/time_zone.h'))"

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
