---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```


# odbconnect

The goal of odbconnect is to provide a DBI-compliant interface to ODBC drivers.

The current implementation uses a modified version of the cpp_odbc and turbodbc
libraries from the [turbodbc](https://github.com/blue-yonder/turbodbc) python
package.

## Benchmarks vs RODBC / RODBCDBI

Simply reading a postgres table with the nytflights13 'flights' database.
```{r}
# First using RODBC / RODBCDBI
library(DBI)
library(RODBCDBI)
rodbc <- dbConnect(RODBCDBI::ODBC(), dsn="database1")
rodbc_query <- dbSendQuery(rodbc, "SELECT * from flights")
system.time(rodbc_result <- dbFetch(rodbc_query))

# Now using odbconnect
library(odbconnect)
odbconnect <- dbConnect(odbconnect::odbconnect(), "DSN=database1")
odbconnect_query <- dbSendQuery(odbconnect, "SELECT * from flights")
system.time(odbconnect_result <- dbFetch(odbconnect_query))

library(tibble)
odbconnect_result

identical(dim(rodbc_result), dim(odbconnect_result))
```

## ODBC Documentation

https://msdn.microsoft.com/en-us/library/ms712628(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/ms714086(v=vs.85).aspx
