// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "odbconnect_types.h"
#include <Rcpp.h>

using namespace Rcpp;

// connect
connection_ptr connect(std::string connection_string);
RcppExport SEXP odbconnect_connect(SEXP connection_stringSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type connection_string(connection_stringSEXP);
    __result = Rcpp::wrap(connect(connection_string));
    return __result;
END_RCPP
}
// connect_info
std::string connect_info(connection_ptr p);
RcppExport SEXP odbconnect_connect_info(SEXP pSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< connection_ptr >::type p(pSEXP);
    __result = Rcpp::wrap(connect_info(p));
    return __result;
END_RCPP
}
