# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

connection_create <- function(x) {
    .Call('odbconnect_connection_create', PACKAGE = 'odbconnect', x)
}

listDrivers <- function() {
    .Call('odbconnect_listDrivers', PACKAGE = 'odbconnect')
}

listDataSources <- function() {
    .Call('odbconnect_listDataSources', PACKAGE = 'odbconnect')
}

