# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

odbconnect_connect <- function(connection_string) {
    .Call('odbconnect_odbconnect_connect', PACKAGE = 'odbconnect', connection_string)
}

connection_info <- function(p) {
    .Call('odbconnect_connection_info', PACKAGE = 'odbconnect', p)
}

connection_quote <- function(p) {
    .Call('odbconnect_connection_quote', PACKAGE = 'odbconnect', p)
}

connection_special <- function(p) {
    .Call('odbconnect_connection_special', PACKAGE = 'odbconnect', p)
}

connection_release <- function(p) {
    invisible(.Call('odbconnect_connection_release', PACKAGE = 'odbconnect', p))
}

connection_begin <- function(p) {
    invisible(.Call('odbconnect_connection_begin', PACKAGE = 'odbconnect', p))
}

connection_commit <- function(p) {
    invisible(.Call('odbconnect_connection_commit', PACKAGE = 'odbconnect', p))
}

connection_rollback <- function(p) {
    invisible(.Call('odbconnect_connection_rollback', PACKAGE = 'odbconnect', p))
}

connection_valid <- function(p) {
    .Call('odbconnect_connection_valid', PACKAGE = 'odbconnect', p)
}

connection_sql_tables <- function(p, catalog_name = "", schema_name = "", table_name = "", table_type = "") {
    .Call('odbconnect_connection_sql_tables', PACKAGE = 'odbconnect', p, catalog_name, schema_name, table_name, table_type)
}

connection_sql_columns <- function(p, column_name = "", catalog_name = "", schema_name = "", table_name = "") {
    .Call('odbconnect_connection_sql_columns', PACKAGE = 'odbconnect', p, column_name, catalog_name, schema_name, table_name)
}

result_release <- function(r) {
    invisible(.Call('odbconnect_result_release', PACKAGE = 'odbconnect', r))
}

result_active <- function(r) {
    .Call('odbconnect_result_active', PACKAGE = 'odbconnect', r)
}

result_completed <- function(r) {
    .Call('odbconnect_result_completed', PACKAGE = 'odbconnect', r)
}

new_result <- function(p, sql, size = 1024L) {
    .Call('odbconnect_new_result', PACKAGE = 'odbconnect', p, sql, size)
}

result_fetch <- function(r, n_max = -1L) {
    .Call('odbconnect_result_fetch', PACKAGE = 'odbconnect', r, n_max)
}

column_info <- function(r) {
    invisible(.Call('odbconnect_column_info', PACKAGE = 'odbconnect', r))
}

result_bind <- function(r, sql, params) {
    invisible(.Call('odbconnect_result_bind', PACKAGE = 'odbconnect', r, sql, params))
}

result_execute <- function(r) {
    invisible(.Call('odbconnect_result_execute', PACKAGE = 'odbconnect', r))
}

result_insert_dataframe <- function(r, df) {
    invisible(.Call('odbconnect_result_insert_dataframe', PACKAGE = 'odbconnect', r, df))
}

result_rows_affected <- function(r) {
    .Call('odbconnect_result_rows_affected', PACKAGE = 'odbconnect', r)
}

result_row_count <- function(r) {
    .Call('odbconnect_result_row_count', PACKAGE = 'odbconnect', r)
}

column_types <- function(df) {
    invisible(.Call('odbconnect_column_types', PACKAGE = 'odbconnect', df))
}

