# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

connect <- function(connection_string) {
    .Call('odbconnect_connect', PACKAGE = 'odbconnect', connection_string)
}

connect_info <- function(p) {
    .Call('odbconnect_connect_info', PACKAGE = 'odbconnect', p)
}

query <- function(p, sql, size = 4096L) {
    .Call('odbconnect_query', PACKAGE = 'odbconnect', p, sql, size)
}

fetch <- function(c) {
    .Call('odbconnect_fetch', PACKAGE = 'odbconnect', c)
}

column_info <- function(c) {
    invisible(.Call('odbconnect_column_info', PACKAGE = 'odbconnect', c))
}

has_completed <- function(c) {
    .Call('odbconnect_has_completed', PACKAGE = 'odbconnect', c)
}

get_tables <- function(p) {
    .Call('odbconnect_get_tables', PACKAGE = 'odbconnect', p)
}

statement_create <- function(con, sql) {
    .Call('odbconnect_statement_create', PACKAGE = 'odbconnect', con, sql)
}

row_count <- function(rs) {
    .Call('odbconnect_row_count', PACKAGE = 'odbconnect', rs)
}

